### ISSUE TITLE
просто database.properties

### ISSUE THREAD

**Issue by niallrox** [oaoaoaoaoaoammmm/reconstruction_1#10]
https://github.com/oaoaoaoaoaoammmm/reconstruction_1/blob/250f87763d437b8e1e9bf1719cc4e099d8bc39a4/src/main/java/org/example/repository/DragonRepo.java#L45

**Comment by oaoaoaoaoaoammmm** [comment]
а иначе он не видит файл

**Comment by niallrox** [comment]
Thread.currentThread().getContextClassLoader().getResourceAsStream("database.properties");
