### ISSUE TITLE
Не делай принтлн и используй аннотацию slf4j всето log

### ISSUE THREAD

**Issue by niallrox** [oaoaoaoaoaoammmm/reconstruction_1#6]
https://github.com/oaoaoaoaoaoammmm/reconstruction_1/blob/250f87763d437b8e1e9bf1719cc4e099d8bc39a4/src/main/java/org/example/services/Exit.java#L14

**Comment by oaoaoaoaoaoammmm** [comment]
slf4j почему-то не работает, я сам ума не приложу почему так
